name: Build and Upload APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Step 1: Build APK
      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace

      # Step 2: Set the SHORT_SHA environment variable for artifact naming
      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | head -c 7)" >> $GITHUB_ENV

      # Step 3: List APK build outputs to check if the APK exists
      - name: List build outputs
        run: ls -R ./app/build/outputs/apk

      # Step 4: Upload APK artifact
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CCTV_Viewer_${{ env.SHORT_SHA }}-X5
          path: ./app/build/outputs/apk/release/app-release.apk  # Ensure the path is correct
